# Platform3 Enterprise Deployment Configuration

# Global Configuration
global:
  environment: production
  region: us-east-1
  cluster: platform3-enterprise
  namespace: platform3-enterprise

# Shadow Mode Configuration
shadowMode:
  enabled: true
  trafficMirrorPercentage: 10
  comparisonThreshold: 0.95
  maxLatencyMs: 100
  enabledServices:
    - analytics-service
    - trading-service
    - ml-service
  kafka:
    brokers:
      - kafka-service:9092
    topics:
      marketData: market-data
      shadowResults: shadow-results
  redis:
    url: redis://redis-service:6379
    keyPrefix: "platform3:shadow:"

# Rollback Configuration
rollback:
  enabled: true
  healthCheckInterval: 30000
  thresholds:
    latencyMs: 100
    errorRate: 0.01
    accuracyThreshold: 0.75
    resourceUsage: 0.9
  services:
    - name: analytics-service
      version: "1.0.0"
      previousVersion: "0.9.0"
      healthEndpoint: "http://analytics-service:3001/health"
      rollbackCommand: "kubectl rollout undo deployment/analytics-service -n platform3"
      dependencies: []
    - name: trading-service
      version: "1.0.0"
      previousVersion: "0.9.0"
      healthEndpoint: "http://trading-service:3002/health"
      rollbackCommand: "kubectl rollout undo deployment/trading-service -n platform3"
      dependencies: ["analytics-service"]
    - name: user-service
      version: "1.0.0"
      previousVersion: "0.9.0"
      healthEndpoint: "http://user-service:3003/health"
      rollbackCommand: "kubectl rollout undo deployment/user-service -n platform3"
      dependencies: []
    - name: api-gateway
      version: "1.0.0"
      previousVersion: "0.9.0"
      healthEndpoint: "http://api-gateway:3000/health"
      rollbackCommand: "kubectl rollout undo deployment/api-gateway -n platform3"
      dependencies: ["analytics-service", "trading-service", "user-service"]

# Monitoring Configuration
monitoring:
  enabled: true
  metricsInterval: 30000
  businessMetrics: true
  alertThresholds:
    latencyP99: 100
    errorRate: 0.01
    throughput: 100
    accuracy: 0.75
    availability: 0.999
  services:
    - analytics-service
    - trading-service
    - user-service
    - api-gateway
    - ml-service
  prometheus:
    scrapeInterval: 15s
    evaluationInterval: 15s
  grafana:
    dashboards:
      - platform3-overview
      - service-metrics
      - business-metrics
      - trading-performance

# CI/CD Configuration
cicd:
  enabled: true
  pipeline:
    stages:
      - security-scan
      - build-and-test
      - integration-tests
      - performance-tests
      - shadow-deployment
      - production-deployment
  deployment:
    strategy: blue-green
    canaryPercentage: 10
    rollbackOnFailure: true
  testing:
    indicators:
      testAll67: true
      performanceThreshold: 100ms
      accuracyThreshold: 0.95
  security:
    vulnerabilityScanning: true
    dependencyCheck: true
    codeAnalysis: true

# Infrastructure Configuration
infrastructure:
  redis:
    cluster: true
    nodes: 3
    memory: "2Gi"
    persistence: true
  kafka:
    brokers: 3
    replicationFactor: 3
    partitions: 12
    retention: "7d"
  database:
    type: postgresql
    cluster: true
    nodes: 3
    storage: "100Gi"
    backup:
      enabled: true
      schedule: "0 2 * * *"
      retention: "30d"

# Security Configuration
security:
  tls:
    enabled: true
    certManager: true
  authentication:
    type: jwt
    issuer: "platform3-auth"
  authorization:
    rbac: true
  networkPolicies:
    enabled: true
    defaultDeny: true
  podSecurityPolicies:
    enabled: true
    runAsNonRoot: true

# Compliance Configuration
compliance:
  auditLogging: true
  dataRetention: "7y"
  encryption:
    atRest: true
    inTransit: true
  regulations:
    - MiFID II
    - GDPR
    - SOX
    - Basel III
  reporting:
    enabled: true
    schedule: "0 0 * * 0"  # Weekly
    storage: "s3://platform3-compliance/"

# Performance Targets
performance:
  latency:
    p50: 10ms
    p95: 50ms
    p99: 100ms
  throughput:
    requestsPerSecond: 10000
    tradesPerSecond: 1000
  availability: 99.99%
  accuracy: 95%

# Business Metrics
business:
  trading:
    accuracyTarget: 78%
    maxDrawdown: 5%
    sharpeRatio: 2.0
  risk:
    maxPositionSize: 2%
    stopLoss: 1%
    maxDailyLoss: 3%
  performance:
    profitTarget: 15%
    winRate: 60%
